FROM python:3.11-alpine

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY app.py .

EXPOSE 5000

CMD ["python", "app.py"]